---
title: 'Figures & Analysis'
author: "Danielle Dempsey"
date: "`r Sys.Date()`"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---
  
```{r, echo = FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, fig.width=9, message=FALSE)

library(data.table)    # import example data
library(dplyr)         # data manipulation 
library(DT)            # interactive tables
library(ggplot2)       # figures
library(ggsflabel)
library(ggspatial)
library(glue)
library(here)          # relative files paths
library(leaflet)       # interactive map   
library(lubridate)
library(sf)            # static map for paper
library(strings)       # convert_depth_to_ordered_factor() function
library(tgc)           # season functions
library(plotly)


dt_options <- list(
      dom = 'ft',
      paging = FALSE,
      searching = TRUE,
      scrollY = "500px",
      scrollX = "500px",
      pageLength = 500,
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

theme_set(theme_light())

```

```{r}

# import data
dat_raw <- import_strings_data(
  add_county_col = FALSE,
  county = c("Halifax", "Guysborough_Dover Bay", "Lunenburg")
) %>%
  filter(VARIABLE == "Temperature") %>% 
  select(-WATERBODY, -LEASE, -VARIABLE, -SENSOR, -DEPLOYMENT_PERIOD, 
         -UNITS, -MOORING) %>% 
  filter(
    STATION == "Flat Island" | 
      STATION == "Beaver Point" | 
      STATION == "Madeline Point"
  ) %>% 
  convert_depth_to_ordered_factor() %>% 
  mutate(
    STATION = ordered(
      STATION, levels = c("Madeline Point", "Beaver Point", "Flat Island")
    )
  )

colour_pal <- get_colour_palette(dat_raw)

```

## Station Map

```{r, echo=FALSE}

dat_map <- dat_raw %>% 
  distinct(STATION, .keep_all = TRUE) 

dat_map %>% 
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)%>%
  addMarkers(~LONGITUDE, ~LATITUDE, label = ~STATION)

```


```{r, echo=FALSE, eval=FALSE}

dat_map <- dat_map %>% 
  mutate(
    SEASON = case_when(
      STATION == "Flat Island" ~ "Long Season",
      STATION == "Beaver Point" ~ "Medium Season",
      STATION == "Madeline Point" ~ "Short Season"
    ),
    LABEL = glue("{STATION} \n ({SEASON})")) %>% 
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326, agr = "constant") 

map_box <- data.frame(Long = c(-66, -59.9), Lat = c(43.5, 47)) %>%
  st_as_sf(coords = c("Long", "Lat"), crs = 4326)

ggplot() +
  geom_sf(data = map_box) +
  annotation_map_tile(type = "cartolight", zoomin = -1) +
  geom_sf(data = dat_map) +
  geom_sf_label(
    data = dat_map, aes(label = LABEL),
    label.size = NA, fill = NA, nudge_y = -0.25, size = 2.7
  ) +
  scale_x_continuous(breaks = c(seq(-60, -66, -2))) +
  scale_y_continuous(breaks = c(seq(44, 47, 1))) +
  annotation_scale(location = "br") +
  annotation_north_arrow(
    location = "tl", which_north = "true",
    height = unit(1, "cm"),
    width = unit(1, "cm")
  ) +
  theme(axis.title = element_blank(),
        text = element_text(size = 10))

ggsave(
  filename = "figure1.png",
  path = here("figs"),
  device = "png",
  width = 11.2, height = 8, units = "cm",
  dpi = 600
)

```




```{r, message=FALSE, warning=FALSE}

dat_seasons <- fread(here("results/dat_seasons.csv"), data.table = FALSE)
# gap_table <- fread(here("results/gap_table.csv"), data.table = FALSE)
dd <- fread(here("results/dd.csv"), data.table = FALSE)
tgc_table <- fread(here("results/tgc_table.csv"), data.table = FALSE)
dat_filt <- fread(here("results/dat_filt.csv"), data.table = FALSE)

```


```{r, echo=FALSE}
n_days <- 14
text_size <- 8
plot_theme <- theme(axis.text = element_text(size = text_size))

```


## Growing Seasons {.tabset}

### Madeline Point (Short Season)

```{r, echo=FALSE, message=FALSE}

short_filt <- dat_filt %>%
  filter(STATION == "Madeline Point")

min_timestamp <- min(short_filt$TIMESTAMP) - days(n_days)
max_timestamp <- max(short_filt$TIMESTAMP) + days(n_days)

short_raw <- dat_raw %>% 
  filter(STATION == "Madeline Point",
         TIMESTAMP >= min_timestamp, TIMESTAMP <= max_timestamp)

p2 <- plot_filtered_data(short_raw, short_filt,
                         date_breaks_major = "1 month",
                         date_labels_format = "%Y-%b", 
                         plotly_friendly = FALSE) +
  plot_theme
  
p2

```


### Beaver Point (Medium Season)

```{r, echo=FALSE, message=FALSE}

med_filt <- dat_filt %>%
  filter(STATION == "Beaver Point")

min_timestamp <- min(med_filt$TIMESTAMP) - days(n_days)
max_timestamp <- max(med_filt$TIMESTAMP) + days(n_days)

med_raw <- med_raw %>% 
  filter(STATION == "Beaver Point",
         TIMESTAMP >= min_timestamp, TIMESTAMP <= max_timestamp)

p2 <- plot_filtered_data(med_raw, med_filt,
                         date_breaks_major = "1 month",
                         date_labels_format = "%Y-%b", 
                         plotly_friendly = FALSE) +
  plot_theme
  
p2

```


```{r, eval=FALSE}

fig_width <- 19
fig_height <- 7

ggsave(
  p2,
  filename = "figure2.png",
  path = here("figs"),
  device = "png",
  width = fig_width, height = fig_height, units = "cm",
  dpi = 600
)

```


## Degree Days {.tabset}

### Figure 
```{r}

p <- ggplot(dd, aes(STATION, n_degree_days, fill = DEPTH,
                    text = paste(
                      "Depth: ", DEPTH, "m", "\n",
                      "Average Temp: ", AVG_TEMPERATURE, "\n",
                      "Growing Days: ", n_growing_days, "\n",
                      "Degree Days: ", n_degree_days))
) +
  geom_point(pch = 21, size = 4,
             position = position_jitter(width = 0.05, height = 0, seed = 10)) +
  scale_fill_manual("Depth (m)", values = colour_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Number of Degree Days") +
  theme_light()

ggplotly(p, tooltip = "text") %>%
  config(
    modeBarButtonsToRemove = list(
      "toggleSpikelines", "autoScale2d", "select2d", "lasso2d",
      "hoverCompareCartesian", "zoom2d"
    ),
    displaylogo = FALSE,
    toImageButtonOptions = list(
      format = "png",
      filename = "degree_days",
      width = 1100,
      height = 1100
    )) %>%
  layout(
    margin = list(b = 90, l = 90) # to fully display the x and y axis labels
  )

```

### Table
```{r echo=FALSE}

dd %>%
  mutate(
    START_SEASON = format(as_date(START_SEASON)),
    END_SEASON = format(as_date(END_SEASON))
  ) %>% 
  arrange(STATION) %>% 
  datatable(
    rownames = FALSE, options = dt_options, 
    caption = "Figure 1: Degree days after applying season and heat stress filters."
  )

```
Note: Partial STOCKED_DAYS caused by the times of END_SEASON and START_SEASON (not shown).

## Thermal Growth Coefficient Model {.tabset}


### Figure
```{r}

p <-  ggplot(tgc_table, aes(x = factor(TGC), y = TGC_INITIAL_WEIGHT, fill = DEPTH,
             text = paste(
                      "Depth: ", DEPTH, "m", "\n",
                      "Average Temp: ", AVG_TEMPERATURE, "\n",
                      "Growing Days: ", n_growing_days, "\n",
                      "Degree Days: ", n_degree_days, "\n",
                      "Initial Weight: ", TGC_INITIAL_WEIGHT ))) +
  geom_point(
    pch = 21, size = 3, alpha = 0.75,
    position = position_jitter(width = 0.15, height = 0, seed = 10)
  ) +
  scale_fill_manual("Depth (m)", values = colour_pal, drop = FALSE) +
  scale_x_discrete("TGC Value") +
  scale_y_continuous("Initial Weight (kg)") +
  facet_wrap(~STATION)


ggplotly(p, tooltip = "text") %>%
  config(
    modeBarButtonsToRemove = list(
      "toggleSpikelines", "autoScale2d", "select2d", "lasso2d",
      "hoverCompareCartesian", "zoom2d"
    ),
    displaylogo = FALSE,
    toImageButtonOptions = list(
      format = "png",
      filename = "degree_days",
      width = 1100,
      height = 1100
    )) %>%
  layout(
    margin = list(b = 90, l = 90) # to fully display the x and y axis labels
  )

```


### Table

```{r}

tgc_table %>%
  select(-START_SEASON, -END_SEASON) %>%
  arrange(STATION, DEPTH) %>%
  datatable(rownames = FALSE, options = dt_options)

```











