---
title: 'Degree Days'
author: "Danielle Dempsey"
date: "`r Sys.Date()`"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---
  
```{r, echo = FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, fig.width=9, message=FALSE)

library(data.table)    # import example data
library(dplyr)         # data manipulation 
library(DT)            # interactive tables
library(ggplot2)       # figures
library(here)          # relative files paths
library(strings)       # convert_depth_to_ordered_factor() function
library(tgc)           # season functions
library(plotly)
library(lubridate)

dt_options <- list(
      dom = 'ft',
      paging = FALSE,
      searching = TRUE,
      scrollY = "500px",
      pageLength = 500,
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

theme_set(theme_light())

```

```{r}

# import data
dat_raw <- tibble(fread(here("data/TGC_temperature_data.csv"))) %>% 
  select(-WATERBODY, -LEASE, -LATITUDE, -LONGITUDE) %>% 
  filter(!(STATION == "Birchy Head" & DEPTH == 2)) %>% 
  convert_depth_to_ordered_factor()

colour_pal <- get_colour_palette(dat_raw)

```

## Growing Seasons {.tabset}

```{r, message=FALSE, warning=FALSE}

#dat_filt <- filter_in_growing_seasons(dat_raw)

# data to plot
# -- CAN send this to count_degree_days() (but NOT if heat stress events are filtered)
dat_seasons <-  dat_raw %>% 
  filter_in_growing_seasons() %>% 
  filter((STATION == "Birchy Head" & SEASON == "S2") |
           (STATION == "Beaver Point" & SEASON == "S2") |
           (STATION == "Rook Island" & SEASON == "S1")
  )

dat_filt <- dat_seasons %>% 
  filter_out_heat_stress_events() %>% 
  convert_depth_to_ordered_factor() 

# summary table
seasons_table <- dat_filt %>% 
  group_by(STATION, SEASON, DEPTH) %>% 
  summarise(START_SEASON = min(TIMESTAMP),
            END_SEASON = max(TIMESTAMP)) %>% 
  ungroup() %>% 
  mutate(
    SEASON_DAYS = difftime(END_SEASON, START_SEASON, units = "days"),
    SEASON_DAYS = as.numeric(round(SEASON_DAYS, digits = 2)),
    SEASON_MONTHS = round(SEASON_DAYS / 30, digits = 2)
  ) %>% 
  #select(-SEASON, - SEASON_DAYS) %>% 
  arrange(STATION,  DEPTH)

```


### Birchy Head

```{r}

dat_filt %>%
  filter(STATION == "Birchy Head") %>%
  plot_temperature_at_depth(
   # facet_var = "DEPTH",
    colour_palette = colour_pal,
    date_breaks_major = "2 month",
    date_labels_format = "%Y-%b"
  )


plot_filtered_data(filter(dat_raw, STATION == "Birchy Head"),
                   filter(dat_filt, STATION == "Birchy Head"))

```

### Beaver Point

```{r}

dat_filt %>%
  filter(STATION == "Beaver Point") %>%
  plot_temperature_at_depth(
   # facet_var = "DEPTH",
    colour_palette = colour_pal,
    date_breaks_major = "1 month",
    date_labels_format = "%Y-%b"
  ) #+
  # annotate("rect",
  #          xmin = as_datetime("2018-06-01"), 
  #          xmax = as_datetime("2018-06-02"),
  #          ymin = -5, 
  #          ymax = 20, col = "grey")


plot_filtered_data(filter(dat_raw, STATION == "Beaver Point"),
                   filter(dat_filt, STATION == "Beaver Point"))


```


### Rook Island

```{r}

dat_seasons %>%
  filter(STATION == "Rook Island") %>%
  plot_temperature_at_depth(
   # facet_var = "DEPTH",
    colour_palette = colour_pal,
    date_breaks_major = "1 month",
    date_labels_format = "%Y-%b"
  )

plot_filtered_data(filter(dat_raw, STATION == "Rook Island"),
                   filter(dat_filt, STATION == "Rook Island"))

```

### Season Table

```{r echo=FALSE}

seasons_table %>%
  mutate(START_SEASON = format(START_SEASON),
         END_SEASON = format(END_SEASON)) %>% 
  datatable(rownames = FALSE, options = dt_options)

```

## Degree Days {.tabset}

```{r}

# this includes SEASONS that we are not considering
dd1 <- count_degree_days(dat_raw, STATION)

# this only includes the STATION + SEASONS we are interested in
dd2 <- count_degree_days(dat_seasons, STATION)

# can't send dat_filt because the function needs to know where to find the heat stress intervals (instead of just having a gap) 
# is there a way to write a good error message for this?
# count_degree_days(dat_filt, STATION)
# count_growing_days(dat_filt, STATION)


dd <- count_degree_days(dat_seasons, STATION)


plot_degree_days(dd, facet_var = "STATION")

```

### Figure

```{r}

p <- ggplot(dd, aes(STATION, n_degree_days, col = DEPTH,
                    text = paste(
                      "Depth: ", DEPTH, "m", "\n",
                      "Average Temp: ", AVG_TEMPERATURE, "\n",
                      "Growing Days: ", n_growing_days, "\n",
                      "Degree Days: ", n_degree_days)) 
) +
  geom_point() +
  scale_colour_manual("Depth (m)", values = colour_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "# degree days") +
  theme_light()

ggplotly(p, tooltip = "text") %>% 
  config(
    modeBarButtonsToRemove = list(
      "toggleSpikelines", "autoScale2d", "select2d", "lasso2d",
      "hoverCompareCartesian", "zoom2d"
    ),
    displaylogo = FALSE,
    toImageButtonOptions = list(
      format = "png",
      filename = "degree_days",
      width = 1100,
      height = 1100
    )) %>%
  layout(
    margin = list(b = 90, l = 90) # to fully display the x and y axis labels
  )

```

### Table

```{r}

dd %>%
  select(-SEASON, -START_SEASON, -END_SEASON) %>% 
  datatable(rownames = FALSE, options = dt_options)

```


## Thermal Growth Model


```{r}

w_t <- 5
tgc <- c(0.25, 0.3, 0.35)

tgc_table <- TGC_calculate_initial_weight(dd, final_weight = w_t, tgc = tgc)


x <- dat_seasons %>% 
  count_degree_days(STATION) %>% 
  TGC_calculate_initial_weight(final_weight = w_t, tgc = tgc)

```


```{r}

p <-  ggplot(tgc_table, aes(x = factor(TGC), y = TGC_INITIAL_WEIGHT, col = DEPTH,
             text = paste(
                      "Depth: ", DEPTH, "m", "\n",
                      "Average Temp: ", AVG_TEMPERATURE, "\n",
                      "Growing Days: ", n_growing_days, "\n",
                      "Degree Days: ", n_degree_days, "\n",
                      "Initial Weight: ", TGC_INITIAL_WEIGHT ))) +
  geom_point() +
  scale_colour_manual("Depth (m)", values = colour_pal, drop = FALSE) +
  scale_x_discrete("TGC Value") +
  scale_y_continuous("Initial Weight (kg)") +
  facet_wrap(~STATION)


ggplotly(p, tooltip = "text") %>% 
  config(
    modeBarButtonsToRemove = list(
      "toggleSpikelines", "autoScale2d", "select2d", "lasso2d",
      "hoverCompareCartesian", "zoom2d"
    ),
    displaylogo = FALSE,
    toImageButtonOptions = list(
      format = "png",
      filename = "degree_days",
      width = 1100,
      height = 1100
    )) %>%
  layout(
    margin = list(b = 90, l = 90) # to fully display the x and y axis labels
  )

```











